#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
# Script to execute postProcess, all functionObjects in system/controlDict are executed
#------------------------------------------------------------------------------

runApplication chtMultiRegionFoam -postProcess

#------------------------------------------------------------------------------
