#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
# Script to run the whole case from scratch
#------------------------------------------------------------------------------

rm -rf constant/polyMesh/sets

runApplication blockMesh
runApplication surfaceFeatureExtract

runApplication snappyHexMesh -overwrite

runApplication splitMeshRegions -cellZones -overwrite

rm -rf 0
cp -r 0.orig 0

for region in $(foamListRegions solid)
do
    rm -f 0/$region/{nut,alphat,epsilon,k,U,p_rgh}
    rm -f processor*/0/$region/{nut,alphat,epsilon,k,U,p_rgh}
done

# change directonarys for 0 directionary and all regions 
for region in $(foamListRegions)
do
    runApplication -s $region changeDictionary -region $region
done

# Decompose
runApplication decomposePar -allRegions

# run solver
runParallel chtMultiRegionFoam

# Reconstruct
runApplication reconstructPar -allRegions

# create files with coordinates of cell centres
for region in $(foamListRegions)
do
   runApplication -s $region postProcess -func writeCellCentres -region $region -time 0
done

# move all logs in new folder
mkdir logs
mv log.* logs

# create -foam file for Paraview
touch shippingBox.foam
#------------------------------------------------------------------------------
