#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh | tee log.blockMesh
runApplication topoSet | tee log.topoSet

restore0Dir

splitMeshRegions -cellZones -overwrite | tee log.splitMeshRegions

# change directonarys for 0 directionary and all regions 
for region in $(foamListRegions)
do
    runApplication -s $region changeDictionary -region $region
done

# run solver
chtMultiRegionFoam | tee log.chtMultiRegionFoam

# create files with coordinates of cell centres
for region in $(foamListRegions)
do
    postProcess -func writeCellCentres -region $region -time 0
done

# move all logs in new folder
mkdir logs
mv log.* logs

# create -foam file for Paraview
touch shippingBox.foam
#------------------------------------------------------------------------------
