#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
runApplication topoSet 

restore0Dir

runApplication splitMeshRegions -cellZones -overwrite | tee log.splitMeshRegions

# change directonarys for 0 directionary and all regions 
for region in $(foamListRegions)
do
    runApplication -s $region changeDictionary -region $region
done

# Decompose
runApplication decomposePar -allRegions

# run solver
runParallel chtMultiRegionFoam

# Reconstruct
runApplication reconstructPar -allRegions

# create files with coordinates of cell centres
for region in $(foamListRegions)
do
   postProcess -func writeCellCentres -region $region -time 0
done

# move all logs in new folder
mkdir logs
mv log.* logs

# create -foam file for Paraview
touch shippingBox.foam
#------------------------------------------------------------------------------
