#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------
# Script to clean the whole case to essential files for Allrun
#------------------------------------------------------------------------------

cleanCase0

rm -f allVisibleFaces.obj

rm -rf logs
rm -rf VTK
rm -rf constant/cellToRegion
rm -rf constant/*/polyMesh  # region meshes

rm -f constant/airOutside/F
rm -f constant/airOutside/constructMap*
rm -f constant/airOutside/finalAgglom
rm -f constant/airOutside/globalFaceFaces
rm -f constant/airOutside/mapDist
rm -f constant/airOutside/visibleFaceFaces

#------------------------------------------------------------------------------
