#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------
# Script to clean the whole case to essential files for Allrun
#------------------------------------------------------------------------------

cleanCase0

rm -rf logs
rm -rf VTK
rm -rf constant/cellToRegion
rm -rf constant/*/polyMesh  # region meshes

#------------------------------------------------------------------------------
