#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------
# This script is used to delete all time directories, so that a new simulation
# can be run, without deleting the mesh and regions
#------------------------------------------------------------------------------

#removes all time directorys in the case
foamListTimes -rm

#removes all time directories in the processors
for i in processor*
do
    foamListTimes -case $i -rm
done

#------------------------------------------------------------------------------
