#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
# Script to run changeDictionaryDict for all solid regions
#------------------------------------------------------------------------------

for region in $(foamListRegions solid)
do
    runParallel -s $region changeDictionary -region $region
done

#------------------------------------------------------------------------------
