#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
# Script to update region
#------------------------------------------------------------------------------

region=${1:-airInside}

runParallel -s $region changeDictionary -region $region -latestTime