#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
# Script to reconstruct the case
#------------------------------------------------------------------------------

for time in $(foamListTimes -processor) 
do
runApplication reconstructPar -allRegions -newTimes -time 0:$time
rm -rf processor*/$time
done

#------------------------------------------------------------------------------
